### ISSUE TITLE
S5: Widen Minotaur encounter area so Player can get preparation time 

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/Struggle_For_Freedom#5]
Noted by @cooljeanius in Feedback

**Comment by cooljeanius** [comment]
I mean personally I'd just prefer they spawn as slowed (at least on easy), but whatever works...

**Comment by cooljeanius** [comment]
> Closes via [51082e5](https://github.com/knyghtmare/Struggle_For_Freedom/commit/51082e5d98c433a45e6f95887c7053401c30ad7b)

Let me know once there's a release containing this commit; I'm still letting the add-on manager manage updates for this one, rather than cloning it from git

**Comment by cooljeanius** [comment]
Well, I was able to beat this scenario now at least; replay attached 
[SFF-Across The Dark Hills replay 20221122-183831.gz](https://github.com/knyghtmare/Struggle_For_Freedom/files/10071871/SFF-Across.The.Dark.Hills.replay.20221122-183831.gz)
